2025-06-22 12:33:52.655 -06:00 [ERR] Failed executing DbCommand (59ms) [Parameters=[], CommandType='"Text"', CommandTimeout='30']
SELECT [p].[Id], [p].[AnioPublicacion], [p].[CategoriaId], [p].[ClasificacionEdad], [p].[Descripcion], [p].[Editorial], [p].[EsPersonalizable], [p].[Estado], [p].[idAutor], [p].[idGeneroProducto], [p].[Nombre], [p].[Precio], [p].[PromedioValoracion], [p].[Stock], [a].[idAutor], [s].[Id], [s].[Estado], [s].[Nombre], [s].[ProductoId], [s].[CategoriaId], [s0].[Id], [s0].[Descripcion], [s0].[ProductoId], [s0].[EtiquetaId], [p2].[idPromocion], [p2].[CategoriaId], [p2].[DescuentoPorcentaje], [p2].[Estado], [p2].[FechaFin], [p2].[FechaInicio], [p2].[Nombre], [p2].[ProductoId], [p2].[TipoPromocionId], [p3].[Id], [p3].[ProductoId], [p3].[Ruta], [a].[descripcion]
FROM [Productos] AS [p]
LEFT JOIN [Autor] AS [a] ON [p].[idAutor] = [a].[idAutor]
LEFT JOIN (
    SELECT [c].[Id], [c].[Estado], [c].[Nombre], [p0].[ProductoId], [p0].[CategoriaId]
    FROM [ProductoCategorias] AS [p0]
    INNER JOIN [Categorias] AS [c] ON [p0].[CategoriaId] = [c].[Id]
) AS [s] ON [p].[Id] = [s].[ProductoId]
LEFT JOIN (
    SELECT [e].[Id], [e].[Descripcion], [p1].[ProductoId], [p1].[EtiquetaId]
    FROM [ProductoEtiquetas] AS [p1]
    INNER JOIN [Etiquetas] AS [e] ON [p1].[EtiquetaId] = [e].[Id]
) AS [s0] ON [p].[Id] = [s0].[ProductoId]
LEFT JOIN [Promociones] AS [p2] ON [p].[Id] = [p2].[ProductoId]
LEFT JOIN [ProductoImagenes] AS [p3] ON [p].[Id] = [p3].[ProductoId]
ORDER BY [p].[Id], [a].[idAutor], [s].[ProductoId], [s].[CategoriaId], [s].[Id], [s0].[ProductoId], [s0].[EtiquetaId], [s0].[Id], [p2].[idPromocion]
2025-06-22 12:33:53.011 -06:00 [ERR] An exception occurred while iterating over the results of a query for context type 'CultureOnline.Infraestructure.Data.CultureOnlineContext'.
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'CategoriaId'.
Invalid column name 'idGeneroProducto'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__211_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
ClientConnectionId:b0ed1bed-9591-4327-8dd7-d9fa19c0291a
Error Number:207,State:1,Class:16
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'CategoriaId'.
Invalid column name 'idGeneroProducto'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__211_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
ClientConnectionId:b0ed1bed-9591-4327-8dd7-d9fa19c0291a
Error Number:207,State:1,Class:16
2025-06-22 12:35:06.765 -06:00 [ERR] Failed executing DbCommand (70ms) [Parameters=[], CommandType='"Text"', CommandTimeout='30']
SELECT [p].[Id], [p].[AnioPublicacion], [p].[CategoriaId], [p].[ClasificacionEdad], [p].[Descripcion], [p].[Editorial], [p].[EsPersonalizable], [p].[Estado], [p].[idAutor], [p].[idGeneroProducto], [p].[Nombre], [p].[Precio], [p].[PromedioValoracion], [p].[Stock], [a].[idAutor], [s].[Id], [s].[Descripcion], [s].[ProductoId], [s].[EtiquetaId], [p1].[idPromocion], [p1].[CategoriaId], [p1].[DescuentoPorcentaje], [p1].[Estado], [p1].[FechaFin], [p1].[FechaInicio], [p1].[Nombre], [p1].[ProductoId], [p1].[TipoPromocionId], [p2].[Id], [p2].[ProductoId], [p2].[Ruta], [a].[descripcion]
FROM [Productos] AS [p]
LEFT JOIN [Autor] AS [a] ON [p].[idAutor] = [a].[idAutor]
LEFT JOIN (
    SELECT [e].[Id], [e].[Descripcion], [p0].[ProductoId], [p0].[EtiquetaId]
    FROM [ProductoEtiquetas] AS [p0]
    INNER JOIN [Etiquetas] AS [e] ON [p0].[EtiquetaId] = [e].[Id]
) AS [s] ON [p].[Id] = [s].[ProductoId]
LEFT JOIN [Promociones] AS [p1] ON [p].[Id] = [p1].[ProductoId]
LEFT JOIN [ProductoImagenes] AS [p2] ON [p].[Id] = [p2].[ProductoId]
ORDER BY [p].[Id], [a].[idAutor], [s].[ProductoId], [s].[EtiquetaId], [s].[Id], [p1].[idPromocion]
2025-06-22 12:35:06.882 -06:00 [ERR] An exception occurred while iterating over the results of a query for context type 'CultureOnline.Infraestructure.Data.CultureOnlineContext'.
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'CategoriaId'.
Invalid column name 'idGeneroProducto'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__211_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
ClientConnectionId:61d09deb-08eb-41b9-bd18-d2e785caea27
Error Number:207,State:1,Class:16
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'CategoriaId'.
Invalid column name 'idGeneroProducto'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__211_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
ClientConnectionId:61d09deb-08eb-41b9-bd18-d2e785caea27
Error Number:207,State:1,Class:16
2025-06-22 12:52:39.009 -06:00 [ERR] Failed executing DbCommand (75ms) [Parameters=[], CommandType='"Text"', CommandTimeout='30']
SELECT [p].[Id], [p].[AnioPublicacion], [p].[ClasificacionEdad], [p].[Descripcion], [p].[Editorial], [p].[EsPersonalizable], [p].[Estado], [p].[idAutor], [p].[IdGeneroProductoNavigationIdGenero], [p].[Nombre], [p].[Precio], [p].[PromedioValoracion], [p].[Stock], [a].[idAutor], [s].[Id], [s].[Descripcion], [s].[ProductoId], [s].[EtiquetaId], [p1].[idPromocion], [p1].[CategoriaId], [p1].[DescuentoPorcentaje], [p1].[Estado], [p1].[FechaFin], [p1].[FechaInicio], [p1].[Nombre], [p1].[ProductoId], [p1].[TipoPromocionId], [p2].[Id], [p2].[ProductoId], [p2].[Ruta], [a].[descripcion]
FROM [Productos] AS [p]
LEFT JOIN [Autor] AS [a] ON [p].[idAutor] = [a].[idAutor]
LEFT JOIN (
    SELECT [e].[Id], [e].[Descripcion], [p0].[ProductoId], [p0].[EtiquetaId]
    FROM [ProductoEtiquetas] AS [p0]
    INNER JOIN [Etiquetas] AS [e] ON [p0].[EtiquetaId] = [e].[Id]
) AS [s] ON [p].[Id] = [s].[ProductoId]
LEFT JOIN [Promociones] AS [p1] ON [p].[Id] = [p1].[ProductoId]
LEFT JOIN [ProductoImagenes] AS [p2] ON [p].[Id] = [p2].[ProductoId]
ORDER BY [p].[Id], [a].[idAutor], [s].[ProductoId], [s].[EtiquetaId], [s].[Id], [p1].[idPromocion]
2025-06-22 12:52:39.123 -06:00 [ERR] An exception occurred while iterating over the results of a query for context type 'CultureOnline.Infraestructure.Data.CultureOnlineContext'.
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'IdGeneroProductoNavigationIdGenero'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__211_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
ClientConnectionId:19086037-a552-46e1-b41e-2423a26f5ab5
Error Number:207,State:1,Class:16
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'IdGeneroProductoNavigationIdGenero'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__211_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
ClientConnectionId:19086037-a552-46e1-b41e-2423a26f5ab5
Error Number:207,State:1,Class:16
2025-06-22 12:55:52.597 -06:00 [ERR] Failed executing DbCommand (52ms) [Parameters=[], CommandType='"Text"', CommandTimeout='30']
SELECT [p].[Id], [p].[AnioPublicacion], [p].[ClasificacionEdad], [p].[Descripcion], [p].[Editorial], [p].[EsPersonalizable], [p].[Estado], [p].[GeneroProductoIdGenero], [p].[idAutor], [p].[Nombre], [p].[Precio], [p].[PromedioValoracion], [p].[Stock], [a].[idAutor], [s].[Id], [s].[Descripcion], [s].[ProductoId], [s].[EtiquetaId], [p1].[idPromocion], [p1].[CategoriaId], [p1].[DescuentoPorcentaje], [p1].[Estado], [p1].[FechaFin], [p1].[FechaInicio], [p1].[Nombre], [p1].[ProductoId], [p1].[TipoPromocionId], [p2].[Id], [p2].[ProductoId], [p2].[Ruta], [a].[descripcion]
FROM [Productos] AS [p]
LEFT JOIN [Autor] AS [a] ON [p].[idAutor] = [a].[idAutor]
LEFT JOIN (
    SELECT [e].[Id], [e].[Descripcion], [p0].[ProductoId], [p0].[EtiquetaId]
    FROM [ProductoEtiquetas] AS [p0]
    INNER JOIN [Etiquetas] AS [e] ON [p0].[EtiquetaId] = [e].[Id]
) AS [s] ON [p].[Id] = [s].[ProductoId]
LEFT JOIN [Promociones] AS [p1] ON [p].[Id] = [p1].[ProductoId]
LEFT JOIN [ProductoImagenes] AS [p2] ON [p].[Id] = [p2].[ProductoId]
ORDER BY [p].[Id], [a].[idAutor], [s].[ProductoId], [s].[EtiquetaId], [s].[Id], [p1].[idPromocion]
2025-06-22 12:55:52.695 -06:00 [ERR] An exception occurred while iterating over the results of a query for context type 'CultureOnline.Infraestructure.Data.CultureOnlineContext'.
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'GeneroProductoIdGenero'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__211_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
ClientConnectionId:973a1eaf-60ed-41a3-b2eb-77ea148b980f
Error Number:207,State:1,Class:16
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid column name 'GeneroProductoIdGenero'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__211_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
ClientConnectionId:973a1eaf-60ed-41a3-b2eb-77ea148b980f
Error Number:207,State:1,Class:16
2025-06-22 18:50:11.988 -06:00 [ERR] The view 'Detalle' was not found. Searched locations: ["/Views/Producto/Detalle.cshtml","/Views/Shared/Detalle.cshtml"]
2025-06-22 18:50:13.186 -06:00 [ERR] 
EventId    :3445-250622065013
ErrorList  :The view 'Detalle' was not found. The following locations were searched:
/Views/Producto/Detalle.cshtml
/Views/Shared/Detalle.cshtml
StackTrace :   at Microsoft.AspNetCore.Mvc.ViewEngines.ViewEngineResult.EnsureSuccessful(IEnumerable`1 originalLocations)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultAsync>g__Logged|22_0(ResourceInvoker invoker, IActionResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
   at Libreria.Web.Middleware.ErrorHandlingMiddleware.Invoke(HttpContext context)

2025-06-22 19:09:43.588 -06:00 [ERR] The view 'Detalle' was not found. Searched locations: ["/Views/Producto/Detalle.cshtml","/Views/Shared/Detalle.cshtml"]
2025-06-22 19:09:43.951 -06:00 [ERR] 
EventId    :799-250622070943
ErrorList  :The view 'Detalle' was not found. The following locations were searched:
/Views/Producto/Detalle.cshtml
/Views/Shared/Detalle.cshtml
StackTrace :   at Microsoft.AspNetCore.Mvc.ViewEngines.ViewEngineResult.EnsureSuccessful(IEnumerable`1 originalLocations)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultAsync>g__Logged|22_0(ResourceInvoker invoker, IActionResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
   at Libreria.Web.Middleware.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\Proyecto CultureOnline\MVCCultureOnline\Middleware\ErrorHandlingMiddleware.cs:line 23

2025-06-22 19:14:32.571 -06:00 [ERR] The view 'Detalle' was not found. Searched locations: ["/Views/Producto/Detalle.cshtml","/Views/Shared/Detalle.cshtml"]
2025-06-22 19:14:32.951 -06:00 [ERR] 
EventId    :3205-250622071432
ErrorList  :The view 'Detalle' was not found. The following locations were searched:
/Views/Producto/Detalle.cshtml
/Views/Shared/Detalle.cshtml
StackTrace :   at Microsoft.AspNetCore.Mvc.ViewEngines.ViewEngineResult.EnsureSuccessful(IEnumerable`1 originalLocations)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultAsync>g__Logged|22_0(ResourceInvoker invoker, IActionResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
   at Libreria.Web.Middleware.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\Proyecto CultureOnline\MVCCultureOnline\Middleware\ErrorHandlingMiddleware.cs:line 23

2025-06-22 19:18:48.000 -06:00 [ERR] The view 'Detalle' was not found. Searched locations: ["/Views/Producto/Detalle.cshtml","/Views/Shared/Detalle.cshtml"]
2025-06-22 19:18:48.407 -06:00 [ERR] 
EventId    :3979-250622071848
ErrorList  :The view 'Detalle' was not found. The following locations were searched:
/Views/Producto/Detalle.cshtml
/Views/Shared/Detalle.cshtml
StackTrace :   at Microsoft.AspNetCore.Mvc.ViewEngines.ViewEngineResult.EnsureSuccessful(IEnumerable`1 originalLocations)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultAsync>g__Logged|22_0(ResourceInvoker invoker, IActionResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
   at Libreria.Web.Middleware.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\Proyecto CultureOnline\MVCCultureOnline\Middleware\ErrorHandlingMiddleware.cs:line 23

